accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views 
from django.contrib.auth.views import LogoutView
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^register/guest/$', views.guest_register_page, name='guestRegister'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
]

carts/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^success/$', views.success_home, name='success'),
    url(r'^cartUpdate/$', views.cart_update, name='update'),
]

ec/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from address import views as ad_views
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls import url
from bill.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view 
from marketing.views import MarketingPreferenceUpdateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^checkout/address/use$',ad_views.checkout_address_use_view,name='checkout_address_use'),
    url(r'^checkout/address/create$',ad_views.checkout_address_create_view,name='checkout_address_create'),
    url(r'^product/',include(('product.urls','product'), namespace='product')),
    url(r'^accounts/',include(('accounts.urls','accounts'), namespace='accounts')),
    url(r'^search/',include(('search.urls','search'), namespace='search')),
    url(r'^carts/',include(('carts.urls','carts'), namespace='carts')),
    url(r'api/cart/',cart_detail_api_view,name = 'api-cart'),
    url(r'billing/payment-method/$',payment_method_view,name = 'billing-payment-method'),
    url(r'billing/payment-method/create/$',payment_method_createview,name = 'billing-payment-method-endpoint'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name = 'marketing-pref'),
]   

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings 
from product.models import Product
from ec import views as ec_views
from django.db.models.signals import pre_save, post_save, m2m_changed
import math
# Create your models here.
User = settings.AUTH_USER_MODEL
class CartManager(models.Manager):
    def new_or_get(self, req):
        cart_id = req.session.get("cart_id",None)
        qs = self.get_queryset().filter(id = cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if req.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = req.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new_cart(user=req.user)
            new_obj = True
            req.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new_cart(self, user = None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user = user_obj)



class Cart(models.Model):
    user = models.ForeignKey(User, null = True, blank = True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank = True)
    subtotal = models.DecimalField(default = 0.00,max_digits = 100, decimal_places = 2)
    total = models.DecimalField(default = 0.00,max_digits = 100, decimal_places = 2)
    updated = models.DateTimeField(auto_now = True)
    timestamp = models.DateTimeField(auto_now_add = True)
    objects = CartManager()
    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal!= total:
            instance.subtotal = total
            instance.save()
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal>0:
        instance.total = float(instance.subtotal) + float(instance.subtotal)*float(0.18)
    else:
        instance.total = 0.00
pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from ec import views as ec_views
from .models import Cart
from product.models import Product
from orders.models import Order
from accounts.forms import loginForm, GuestForm
from accounts.models import GuestMail
from bill.models import BillingProfile
from address.forms import AddressForm
from address.models import Address
from django.http import JsonResponse
from django.conf import settings
# Create your views here.

import stripe
STRIPE_SECRET_KEY = getattr(settings,'STRIPE_SECRET_KEY', 'sk_test_vQMUKe3reph39hVffrrTHINx00hLBGvtxN')
STRIPE_PUB_KEY = getattr(settings,'STRIPE_PUB_KEY' ,'pk_test_YAkn6NLTWIOdoYVdXyh0oyLx0048Jhc6NS')
stripe.api_key = STRIPE_SECRET_KEY



def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id": x.id,
            "url": x.get_absolute_url(),
            "name": x.name, 
            "price": x.price
            } 
            for x in cart_obj.products.all()]
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)



def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request,'carts/home.html',{"cart":cart_obj,"user":request.user})

def success_home(request):
    return render(request,'carts/success.html')

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id = product_id)
        except Product.DoesNotExist:
            print("No product")
            return redirect("carts:cartHome")       
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax():
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount": cart_obj.products.count()
            }
            return JsonResponse(json_data, status=200)

    return redirect("carts:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")    
    login_form = loginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    shipping_address_id = request.session.get("shipping_address_id", None)
    billing_address_id = request.session.get("billing_address_id", None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    has_card = False
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        print("Shipping")
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        print("Billing")
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
        has_card = billing_profile.has_card
    if request.method == "POST":
        "check that order is done"
        is_prepared = order_obj.check_done()
        if is_prepared:
            did_charge, crg_msg = billing_profile.charge(order_obj)
            if did_charge:
                order_obj.mark_paid() # sort a signal for us
                request.session['cart_items'] = 0
                del request.session['cart_id']
                if not billing_profile.user:
                    billing_profile.set_cards_inactive()
                return redirect("carts:success")
            else:
                print(crg_msg)
                return redirect("carts:checkout")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
        "has_card" : has_card,
        "publish_key":STRIPE_PUB_KEY
    }
    return render(request, "carts/checkout.html", context)

carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    {% if not billing_profile %}
        <h3 class="text-center">Please Login</h3>
        <br>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=req.build_absolute_uri %}
        <hr>
        <h6 class="text-center">or</h6>
        <br>
        <h3 class="text-center">Continue as Guest</h3>
        <br>
        {% url "accounts:guestRegister" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=req.build_absolute_uri action_url=guest_register_url%}
    {% else %}
        {% if not object.shipping_address %}
        <h3 class="text-center">Shipping Address</h3>   
            <hr>
        <div class="row">
            <div class="col mx-auto col-6">
                {% url "checkout_address_create" as checkout_address_create %}
                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create  address_type='shipping' %}       
            </div>
            <div class="col mx-auto col-6">
                    <h6>Select one of these</h6>
                    <hr>
                {% url "checkout_address_use" as checkout_address_use %}
                {% include 'addresses/previousAddress.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_use %}
            </div>
        </div>
        {% elif  not object.billing_address %}
        <h3 class="text-center">Billing Address</h3>
                <hr>
        <div class="row">
            <div class="col mx-auto col-6">
                {% url "checkout_address_create" as checkout_address_create %}
                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}       
            </div>
            <div class="col mx-auto col-6">
                    <h6>Select one of these</h6>
                    <hr>
                {% url "checkout_address_use" as checkout_address_use %}
                {% include 'addresses/previousAddress.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_use %}
            </div>
        </div>
        {% else %}
            {% if not has_card  %}
            <br>
            <h4 class="text-center">Add Payment Method</h4>
            <br>
            <div class="col-10 col-md-6 mx-auto">
                <div class="stripe-payment-form" data-token="{{publish_key}}" data-next-url="{{request.build_absolute_uri}}" data-btn-title="Add Payment Method"></div>
            </div>
            {% else %}
                <h1 class = "text-center">Confirm Checkout</h1>
                <p><b>Cart Items:</b> {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p><b>Shipping Address:</b> {{ object.shipping_address.get_address}}</p>
                <p><b>Billing Address:</b> {{ object.billing_address.get_address}}</p>
                <p><b>Payment Method :</b> {{billing_profile.default_card}} ( <a href="{{billing_profile.get_payment_method_url}}?next={{request.build_absolute_uri}}">Change</a> )</p>
                <p><b>Cart Total :</b>  &#8377; {{object.cart.total}} </p>
                <p><b>Shipping Total :</b>  &#8377; {{object.shipping_total}}</p>
                <p><b>Order Total :</b>  &#8377; {{object.total}}</p>
                <form class= "form" action="" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Place Order</button>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}
</div>
{% endblock body %}
    

carts/templates/carts/home.html
{% extends 'base.html' %}

{% block body %}
    <hr>
    <h4 class = "text-center" >{{user}} 's  Cart</h4>
    {% if cart.products.exists %}
    <hr>
    <div class="container">
    <table class="table cart-table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">ProductNo</th>
            <th scope="col">Product Name</th>
            <th scope="col">Product Price</th>
            <th></th>
          </tr>
        </thead>
        <tbody class = "cart-body">
            {% for product in cart.products.all %}
                <tr class="cart-product">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{product.get_absolute_url}}" style="text-decoration: None;color:black;" >{{product.title}}</a></td>
                    <td>Rs. {{product.price}}</td>
                    <td>{% include 'carts/snippets/remove-product.html' with product_id=product.id  %}</td>
                </tr>
            {% endfor %}
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <td><b>Subtotal : <span class="cart-subtotal"> Rs. {{cart.subtotal}} </span>  </b></td>
          </tr>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <td><b>Total : <span class="cart-total"> Rs. {{cart.total}} (Including Taxes)</span> </b></td>
          </tr>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <td><a class="btn btn-success" href='{% url "carts:checkout" %}'>Checkout</a></td>
          </tr>
        </tbody>
      </table>
      <div class="cart-item-remove-form" style="display: none;">
          {% include 'carts/snippets/remove-product.html' %}
      </div>

    {% else %}
    <hr>
    <div class = "container text-center">
        <p class = "lead" style="color:red;"> <b> Cart is Empty </b></p>
    </div>
    {% endif %}
    </div>
{% endblock body %}

carts/templates/carts/success.html
{% extends 'base.html' %}

{% block body %}
    

    
<div class="container">
    <h3 class="text-center" >Checkout Successful</h3>
    <hr>
    <h6 class="text-center">Thanks for shopping with us</h6>
</div>

{% endblock body %}