carts/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^success/$', views.success_home, name='success'),
    url(r'^cartUpdate/$', views.cart_update, name='update'),
]

ec/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from address import views as ad_views
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls import url
from bill.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view 
from marketing.views import MarketingPreferenceUpdateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^checkout/address/use$',ad_views.checkout_address_use_view,name='checkout_address_use'),
    url(r'^checkout/address/create$',ad_views.checkout_address_create_view,name='checkout_address_create'),
    url(r'^product/',include(('product.urls','product'), namespace='product')),
    url(r'^accounts/',include(('accounts.urls','accounts'), namespace='accounts')),
    url(r'^search/',include(('search.urls','search'), namespace='search')),
    url(r'^carts/',include(('carts.urls','carts'), namespace='carts')),
    url(r'api/cart/',cart_detail_api_view,name = 'api-cart'),
    url(r'billing/payment-method/$',payment_method_view,name = 'billing-payment-method'),
    url(r'billing/payment-method/create/$',payment_method_createview,name = 'billing-payment-method-endpoint'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name = 'marketing-pref'),
]   

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.conf.urls import url
from . import views as product_views

urlpatterns = [
    
    url(r'^productList/$', product_views.productListView.as_view(),name = 'list'),
    #url(r'^productDetail2/(?P<pk>\d+)/$', product_views.productdetail_view),
    #url(r'^productDetail/(?P<pk>\d+)/$', product_views.productDetailView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$', product_views.productDetailSlugView.as_view(),name = 'detail'),
    #url(r'^productFeaturedDetail/(?P<pk>\d+)/$', product_views.productFeaturedDetailView.as_view()),
    #url(r'^productFeaturedList/$', product_views.productFeaturedListView.as_view())
]

product/models.py
from django.db import models
from django.db.models import Q 
import random
import os
from django.db.models.signals import pre_save, post_save
from ec.utils import unique_slug_generator
from django.urls import reverse
# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1,20303031)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename = new_filename, ext = ext)
    return "product/{new_filename}/{final_filename}".format(new_filename = new_filename, final_filename = final_filename)

class ProductQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured = True)
    def active(self):
        return self.filter(active = True)
    def search(self, query):
        lookups = (Q(title__icontains = query)|
                    Q(description__icontains = query)|
                    Q(price__icontains = query)|
                    Q(tag__title__icontains = query)|
                    Q(tag__icontains = query))
        return self.filter(lookups).distinct()
    

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using = self._db)
    def all(self):
        return self.get_queryset()
    def featured(self):
        return self.get_queryset().featured()
    def active(self):
        return self.get_queryset().active()
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count()==1:
            return qs.first()    
        return None 
    def search(self, query):
        lookups = Q(title__icontains = query) | Q(description__icontains = query) | Q(price__icontains = query)
        return self.get_queryset().active().filter(lookups).distinct()

class Product(models.Model):
    title = models.CharField(max_length = 120)
    slug = models.SlugField(blank = True, unique = True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20)
    image = models.ImageField(upload_to = upload_image_path,null = True, blank = True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def get_absolute_url(self):
        return reverse("product:detail",kwargs = {"slug":self.slug})
    def __str__(self):
        return self.title
    @property
    def name(self):
        return self.title   


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender = Product)

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.http import Http404
from carts.models import Cart
from analytics.mixins import ObjectViewMixin
from .models import Product
# Create your views here.
class productFeaturedListView(ListView):
    template_name = 'productListView.html'
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.featured()


class productFeaturedDetailView(ObjectViewMixin,DetailView):
    template_name = 'productFeaturedDetailView.html'    
    queryset = Product.objects.featured()
    def get_queryset(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        return Product.objects.filter(featured = True)



class productListView(ListView):
    queryset = Product.objects.all()
    template_name = 'productListView.html'
    def get_context_data(self,*args, **kwargs):
        context = super(productListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)###
        context["cart"] = cart_obj
        return context

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(productListView,self).get_context_data(*args, **kwargs)
        return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()
# def productlist_view(req):
#     queryset = Product.objects.all()
#     context = {'object_list':queryset}
#     return render(req,'productListView.html',context)



class productDetailView(ObjectViewMixin,DetailView):
    queryset = Product.objects.all()
    template_name = 'productDetailView.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super(productDetailView,self).get_context_data(*args, **kwargs)
        # print(context)
        return context
    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        qs = Product.objects.filter(id = pk)
        instance = Product.objects.get_by_id(id=pk)
        if instance is None:
            raise Http404("Product doesn't exist")
        return instance

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk = pk)

class productDetailSlugView(ObjectViewMixin,DetailView):
    queryset = Product.objects.all()
    template_name = 'productDetailView.html'

    # def get_context_data(self, *args, **kwaargs):
    def get_context_data(self,*args, **kwargs):
        context = super(productDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)###
        context["cart"] = cart_obj
        return context
    

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        qs = Product.objects.filter(slug = slug)
        instance = Product.objects.get(slug=slug)
        if instance is None:
            raise Http404("Product doesn't exist")
        #object_viewed_signal.send(instance.__class__, instance=instance,request=request)
        return instance


def productdetail_view(req, pk):
    # instance = Product.objects.get(pk=pk)
    # queryset = Product.objects.all()
    # try:
    #     instance = Product.objects.get(id=pk)
    # except Product.DoesNotExist:
    #     print('No product')
    #     raise Http404("Product doesn't exist")
    
    qs = Product.objects.filter(id = pk)
    instance = Product.objects.get_by_id(id=pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    # print(instance)
    # if qs.exists() and qs.count() == 1:
    #     instance = qs.first()
    # else:
        # raise Http404("Product doesn't exist")
    context = {'object':instance}
    return render(req,'productDetailView.html',context)

product/templates/addToCart.html
<form action="{% url 'carts:update' %}" method="POST" data-endpoint="{% url 'carts:update' %}" class="form form-product-ajax">
    {% csrf_token %}
    <input type="hidden" name = "product_id" value="{{product.id}}">
    <span class="submit-span">
        {% if product in  cart.products.all %}
            <button type="submit" class="btn btn-dark"><small> Remove</small></button>
        {% else %}
            <button type="submit" class="btn btn-dark"><small>Add to Cart</small></button>
        {% endif %}
    </span>
</form>

product/templates/productDetailView.html
{% extends 'base.html' %}

{% block body %}
<br>
<br>
<div class="container">
    <div class='row'>
        <div class="col-12 col-md-6">
            {{object.title}} <br><hr>
            {{object.description}} <br>
            {{object.price}} <br>
            {% if object.image  %}
                <img src="{{object.image.url}}" class='img-fluid' alt="Image not found" srcset=""/>
                <br>    
            {% endif %}
        </div>
        <div class="col-12 col-md-6">
            {% include 'addToCart.html' with product=object cart=cart  %}
        </div>
    </div>
</div>
{% endblock body %}
    

product/templates/productFeaturedDetailView.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class='container'>
    {{object.title}} <br>
    {{object.description}} <br>
    {{object.price}} <br>
    <img src="{{object.image.url}}" class='img-fluid' alt="Image not found" srcset=""/>
    <br>
</div>
{% endblock body %}
        

product/templates/productListView.html
{% extends 'base.html' %}

{% block body %}
<br>
{% if request.user.is_authenticated %}

    {% for obj in object_list %}  
    <div class="card mb-3 ml-auto mr-auto" style="max-width: 600px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <a href="{{obj.get_absolute_url}}" >
                    {% if  obj.image %} 
                    <img src="{{obj.image.url}}" style="max-width: 20rem;max-height: 20rem;" class="card-img-top" alt="Image Not found">       
                    {% else %}
                    <img src="" alt="Image Not found" srcset="">
                    {% endif %}
                </a>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                <h5 class="card-title">{{obj.title}}</h5>
                <p class="card-text">{{obj.description | truncatewords:15}}</p>
                <small><p class="card-text"> &#8377; {{obj.price}}</p></small>
                <br>
                {% include 'addToCart.html' with product=obj cart=cart  %}
                <small class="text-muted"><a href="{{obj.get_absolute_url}}" class="card-text">view more</a></small>
                <p><small class="text-muted">Product added on: {{obj.timestamp}}</small></p>
                </div>
            </div>
        </div>
    </div>
    <br>

    {% endfor %}
    
{% else %}

{% for obj in object_list %}
<div class="card mb-3 ml-auto mr-auto" style="max-width: 600px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <a href="#" >
                {% if  obj.image %} 
                <img src="{{obj.image.url}}" style="max-width: 25rem;max-height: 25rem;" class="card-img-top" alt="Image Not found">       
                {% else %}
                <img src="" alt="Image Not found" srcset="">
                {% endif %}
            </a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
            <h5 class="card-title">{{obj.title}}</h5>
            <p class="card-text">{{obj.description | truncatewords:15}}</p>
            <small><p class="card-text"> &#8377; {{obj.price}}</p></small>
            <br>
            {% include 'addToCart.html' with product=obj cart=cart  %}
            <small class="text-muted">To view more please login</small>
            <p><small class="text-muted">Product added on: {{obj.timestamp}}</small></p>
            </div>
        </div>
    </div>
</div>
<br>



{% endfor %}


{% endif %}
{% endblock body %}