accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views 
from django.contrib.auth.views import LogoutView
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^register/guest/$', views.guest_register_page, name='guestRegister'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
]

ec/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from address import views as ad_views
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls import url
from bill.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view 
from marketing.views import MarketingPreferenceUpdateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^checkout/address/use$',ad_views.checkout_address_use_view,name='checkout_address_use'),
    url(r'^checkout/address/create$',ad_views.checkout_address_create_view,name='checkout_address_create'),
    url(r'^product/',include(('product.urls','product'), namespace='product')),
    url(r'^accounts/',include(('accounts.urls','accounts'), namespace='accounts')),
    url(r'^search/',include(('search.urls','search'), namespace='search')),
    url(r'^carts/',include(('carts.urls','carts'), namespace='carts')),
    url(r'api/cart/',cart_detail_api_view,name = 'api-cart'),
    url(r'billing/payment-method/$',payment_method_view,name = 'billing-payment-method'),
    url(r'billing/payment-method/create/$',payment_method_createview,name = 'billing-payment-method-endpoint'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name = 'marketing-pref'),
]   

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [ 
    url(r'^$', views.productSearchListView.as_view(),name = 'list'),
]

templates/about.html
{% extends 'base.html' %}

{% block body %}
<br>

<div class="container">
    <h3 class="text-center">About Us</h3>
    <br>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident, totam adipisci? Autem quibusdam, minus fugit suscipit nemo quam. Optio sit possimus laboriosam dolorem quibusdam illo deserunt minima necessitatibus, impedit in.
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque officia recusandae debitis autem, tenetur eius nisi et. Deleniti cum, corporis in explicabo labore beatae hic illum veritatis sed fuga suscipit! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, nihil laudantium. Quaerat quia facere iure! Vitae, quas fuga quam veniam iure eaque doloribus, totam inventore numquam excepturi dolorem quidem pariatur?
    </p>
</div>
{% endblock body %}
    

templates/base.html
{% load static %}
{% url 'about' as about_url %}
{% url 'home' as home_url %}
{% url 'product:list' as products_url%}
{% url 'contact' as contact_url  %}
{% url 'accounts:login' as login_url %}
{% url 'marketing-pref' as marketing_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'carts:home' as cart_url %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel ="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href='{% static "css/myfile.css" %}'>
    <title>eCom | Welcome !</title>
    <link rel="shortcut icon" href="{% static 'images/brand.jpg' %}" type="image/x-icon">
    <style>
      
      ::-webkit-scrollbar {
        width: 10px;
      }
      
      
      ::-webkit-scrollbar-track {
        box-shadow: inset 0 0 4px grey; 
        border-radius: 10px;
      }
       
      
      ::-webkit-scrollbar-thumb {
        background: black; 
        border-radius: 10px;
      }
      
      ::-webkit-scrollbar-thumb:hover {
        background: grey; 
      }
      </style>      

  </head>   
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black">
        <a class="navbar-brand" href="{{home_url}}">
          <img src="{% static 'images/brand.jpg' %}" width="30" height="30" alt="">
        </a>
        <a class="navbar-brand" href="{{home_url}}">eCom</a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == about_url %}active{% endif %}">
              <a class="nav-link" href="{{about_url}}">About</a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
              <a class="nav-link" href="{{contact_url}}">Contact Us</a>
            </li>
            <li class="nav-item mr-5 {% if request.path == products_url %}active{% endif %}">
              <a class="nav-link" href="{{products_url}}">Products</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li>
              <form action="{% url 'search:list' %}" method="GET" class="form my-2 my-lg-0 search-form">
                <div class="input-group">
                  <input class="form-control" type="search" placeholder="Search" name="q" value="{{request.GET.q}}" aria-label="Search">
                  <span class="input-group-btn">
                   <button class="btn btn-dark" type="submit">Search</button>
                 </span>
                </div>
              </form>
            </li>
            <li class="nav-item {% if request.path == cart_url %}active{% endif %} ">
              <a class="nav-link" href="{{cart_url}}"><i class="fa fa-shopping-cart" aria-hidden="true"><span class="navbar-cart-count">{{request.session.cart_items}}</span></i>
              </a>
            </li>
            
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown {% if request.path == marketing_url %}active{% endif %} ">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-ha>{{request.user}}</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{marketing_url}}" > My Preferences </a>
                    <a class="dropdown-item disabled" href="#" > My Profile </a>
                    <a class="dropdown-item disabled " href="#" > My Orders </a>
                    <a class="dropdown-item disabled " href="#" > My Payments </a>
                    <a class="dropdown-item" href="{{logout_url}}">Logout</a>
                  </div>
                </li>
                
              {% else %}
                <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                  <a class="nav-link" href="{{login_url}}">Login</a>
                </li>
                <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                  <a class="nav-link" href="{{register_url}}">Register</a>
                </li>
              {% endif %}
          </ul>
        </div>
      </nav>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
    <!-- jquery-confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    
    <!-- js render -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.6/jsrender.min.js"></script>
    {% include "js-templates.html" %}
    <!-- stripe-js -->
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="{% static 'css/stripe-style.css' %}" />

    <!-- Secure ajax js -->
    <script type="text/javascript" src="{% static 'js/csrf.ajax.js' %}"></script>
    
    <!-- custom js -->
    <script type="text/javascript" src="{% static 'js/ecommerce.js' %}"></script>
    
    <!-- custom2 js -->
    <script type="text/javascript" src="{% static 'js/ecommerce.main.js' %}"></script>
    
    <div class='container'>
      {% if messages %}
    <div class="alert alert-success messages">
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}<br/>
        </span>
        {% endfor %}
    </div>
    {% endif %}
    {% block body %}{% endblock %}
  </div> 
         
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="text-center">
    <h3>Contact Us</h3>
</div>
<br>
<div style="width:70%" class="container">
    <form  class = "contact-form" action="{% url 'contact' %}" method="POST">
        {% csrf_token %}
            {{form.as_p}}
            <br>
            <div class="container d-flex justify-content-center">
                <input type="submit" class='btn btn-dark' value="Contact Us">
            </div>
    </form>
</div>
{% endblock body %}
    
    

templates/home.html
{% extends 'base.html' %}

{% block body %}
<br>
<h3 class="text-center">Welcome</h3>
    <div class="container">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox" style=" width:100%; height: 500px !important;">
            <div class="carousel-item active">
                <img src="https://specials-images.forbesimg.com/imageserve/5d95d03767dd830006a295b6/960x0.jpg?fit=scale" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>First Implementation</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://cdn.searchenginejournal.com/wp-content/uploads/2017/11/e-commerce-link-building-1520x800.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>Lots of Excitement</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://www.reliablesoft.net/wp-content/uploads/2017/06/ecommerce-seo.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>Inspired!</h5>
                </div>
            </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <marquee behavior="" direction="left">Made for learning! Thanks for Visiting.</marquee>



{% endblock body %}
    

templates/js-templates.html
{% verbatim %}
<script id="stripeTemplate" type="text/x-jsrender">
    <form class = "payment-form" action="" method="post" id="payment-form" data-token="{{:publishKey}}" data-next-url="{{:nextUrl}}">
        <div class="form-row">
            <label for="card-element">
            <b>Enter Credit or Debit card details</b>
            <br>
            </label>
            <div id="card-element" class="form-control">
            <!-- A Stripe Element will be inserted here. -->
            </div>

            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>
        <br>
        <button class='btn btn-success btn-load'>{{:btnTitle}}</button>
    </form>
</script>
{% endverbatim %}